import React from 'react';
import { createGlobalStyle } from 'styled-components';
import { Navbar } from "./Navbar/Navbar";
import { Banner } from "./Banner/Banner";

const GlobalStyle = createGlobalStyle`
  body {
    margin: 0;
    font-family: 'Open Sans', sans-serif;
  }

  h1, h2, h3 {
    font-family: 'Righteous', cursive;
  }

`

function App() {
  return (
    <>
      <GlobalStyle/>
      <Navbar/>
      <Banner/>
      <div>Hello Pizzachu</div>
      <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id dolor eget lectus volutpat viverra. Suspendisse potenti. Nulla sed nunc venenatis, sollicitudin quam porttitor, ultricies nunc. Nullam tempor, urna lobortis bibendum vulputate, turpis leo elementum nulla, eget fermentum metus dolor quis lacus. Mauris arcu mi, elementum sed arcu et, consequat congue sapien. Etiam eu aliquam purus. Aliquam et metus sed ipsum vehicula ullamcorper. Duis eu hendrerit odio. Proin sed nulla vehicula, pellentesque nibh sed, commodo dui. Duis vulputate leo at tellus sagittis, et euismod est congue. Curabitur tempor neque nulla, in pretium mauris imperdiet eu. Vestibulum eu mauris nunc. Nulla feugiat convallis nunc vel placerat. Nullam volutpat porta lectus, id placerat elit fermentum quis. Quisque elementum, sapien non aliquet consectetur, velit nisl dictum nisl, quis faucibus odio nisi sit amet arcu.

Vivamus sit amet sodales purus. Phasellus sem lorem, cursus et felis vel, eleifend egestas nunc. Donec pretium imperdiet magna, faucibus euismod tortor ultricies nec. Nullam pulvinar fermentum purus at dignissim. Praesent in metus nec lorem scelerisque pulvinar sed et libero. Duis sagittis at dui vitae cursus. Quisque ut orci eros. Sed vel lectus quis arcu venenatis aliquet. Sed id lorem ut ipsum consectetur consectetur. Pellentesque efficitur nisi tincidunt orci condimentum, quis auctor massa gravida. In hac habitasse platea dictumst. In magna eros, condimentum nec interdum eget, vehicula nec mi.

Proin vehicula fringilla leo id pretium. Phasellus malesuada ligula urna, sit amet venenatis elit interdum et. Suspendisse urna elit, rhoncus nec luctus vel, imperdiet vitae libero. Duis condimentum nunc magna, sed posuere quam egestas vel. Donec consequat hendrerit risus sit amet commodo. Cras tincidunt vestibulum lectus nec dictum. Donec sed augue scelerisque, luctus orci nec, molestie leo. Duis at libero ullamcorper, congue mauris vel, dignissim erat. Morbi eu iaculis nisl, ut luctus velit. Cras tristique gravida turpis.

Proin eleifend quam sit amet massa congue, in congue tellus efficitur. Donec eleifend nulla et mattis pharetra. Curabitur laoreet hendrerit varius. Curabitur pretium est gravida, malesuada mauris quis, maximus turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus congue tellus quis ultricies ullamcorper. Integer eleifend ligula eu libero consectetur egestas. Vestibulum ornare porta feugiat. Aliquam erat volutpat. Nunc sit amet ante eget ex egestas dapibus sit amet eget dui. Sed sit amet nibh orci.

Donec volutpat quis ligula eget blandit. Etiam nec fermentum diam. Praesent sed vehicula enim, ut faucibus lorem. Proin quis bibendum quam, quis blandit nunc. Vestibulum auctor id tortor vel consectetur. Aliquam vitae elit et urna viverra consequat. Fusce quis maximus magna. Proin eu pellentesque augue, sed malesuada orci. Vestibulum in efficitur nisl, quis blandit justo. Integer non quam vel orci venenatis mattis. Nunc id sapien ultrices, molestie felis id, dictum felis. Proin porta gravida quam at sodales. Nullam pharetra viverra efficitur. Vivamus ut est id tellus sollicitudin tempus. 


Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id dolor eget lectus volutpat viverra. Suspendisse potenti. Nulla sed nunc venenatis, sollicitudin quam porttitor, ultricies nunc. Nullam tempor, urna lobortis bibendum vulputate, turpis leo elementum nulla, eget fermentum metus dolor quis lacus. Mauris arcu mi, elementum sed arcu et, consequat congue sapien. Etiam eu aliquam purus. Aliquam et metus sed ipsum vehicula ullamcorper. Duis eu hendrerit odio. Proin sed nulla vehicula, pellentesque nibh sed, commodo dui. Duis vulputate leo at tellus sagittis, et euismod est congue. Curabitur tempor neque nulla, in pretium mauris imperdiet eu. Vestibulum eu mauris nunc. Nulla feugiat convallis nunc vel placerat. Nullam volutpat porta lectus, id placerat elit fermentum quis. Quisque elementum, sapien non aliquet consectetur, velit nisl dictum nisl, quis faucibus odio nisi sit amet arcu.

Vivamus sit amet sodales purus. Phasellus sem lorem, cursus et felis vel, eleifend egestas nunc. Donec pretium imperdiet magna, faucibus euismod tortor ultricies nec. Nullam pulvinar fermentum purus at dignissim. Praesent in metus nec lorem scelerisque pulvinar sed et libero. Duis sagittis at dui vitae cursus. Quisque ut orci eros. Sed vel lectus quis arcu venenatis aliquet. Sed id lorem ut ipsum consectetur consectetur. Pellentesque efficitur nisi tincidunt orci condimentum, quis auctor massa gravida. In hac habitasse platea dictumst. In magna eros, condimentum nec interdum eget, vehicula nec mi.

Proin vehicula fringilla leo id pretium. Phasellus malesuada ligula urna, sit amet venenatis elit interdum et. Suspendisse urna elit, rhoncus nec luctus vel, imperdiet vitae libero. Duis condimentum nunc magna, sed posuere quam egestas vel. Donec consequat hendrerit risus sit amet commodo. Cras tincidunt vestibulum lectus nec dictum. Donec sed augue scelerisque, luctus orci nec, molestie leo. Duis at libero ullamcorper, congue mauris vel, dignissim erat. Morbi eu iaculis nisl, ut luctus velit. Cras tristique gravida turpis.

Proin eleifend quam sit amet massa congue, in congue tellus efficitur. Donec eleifend nulla et mattis pharetra. Curabitur laoreet hendrerit varius. Curabitur pretium est gravida, malesuada mauris quis, maximus turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus congue tellus quis ultricies ullamcorper. Integer eleifend ligula eu libero consectetur egestas. Vestibulum ornare porta feugiat. Aliquam erat volutpat. Nunc sit amet ante eget ex egestas dapibus sit amet eget dui. Sed sit amet nibh orci.

Donec volutpat quis ligula eget blandit. Etiam nec fermentum diam. Praesent sed vehicula enim, ut faucibus lorem. Proin quis bibendum quam, quis blandit nunc. Vestibulum auctor id tortor vel consectetur. Aliquam vitae elit et urna viverra consequat. Fusce quis maximus magna. Proin eu pellentesque augue, sed malesuada orci. Vestibulum in efficitur nisl, quis blandit justo. Integer non quam vel orci venenatis mattis. Nunc id sapien ultrices, molestie felis id, dictum felis. Proin porta gravida quam at sodales. Nullam pharetra viverra efficitur. Vivamus ut est id tellus sollicitudin tempus. 


Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id dolor eget lectus volutpat viverra. Suspendisse potenti. Nulla sed nunc venenatis, sollicitudin quam porttitor, ultricies nunc. Nullam tempor, urna lobortis bibendum vulputate, turpis leo elementum nulla, eget fermentum metus dolor quis lacus. Mauris arcu mi, elementum sed arcu et, consequat congue sapien. Etiam eu aliquam purus. Aliquam et metus sed ipsum vehicula ullamcorper. Duis eu hendrerit odio. Proin sed nulla vehicula, pellentesque nibh sed, commodo dui. Duis vulputate leo at tellus sagittis, et euismod est congue. Curabitur tempor neque nulla, in pretium mauris imperdiet eu. Vestibulum eu mauris nunc. Nulla feugiat convallis nunc vel placerat. Nullam volutpat porta lectus, id placerat elit fermentum quis. Quisque elementum, sapien non aliquet consectetur, velit nisl dictum nisl, quis faucibus odio nisi sit amet arcu.

Vivamus sit amet sodales purus. Phasellus sem lorem, cursus et felis vel, eleifend egestas nunc. Donec pretium imperdiet magna, faucibus euismod tortor ultricies nec. Nullam pulvinar fermentum purus at dignissim. Praesent in metus nec lorem scelerisque pulvinar sed et libero. Duis sagittis at dui vitae cursus. Quisque ut orci eros. Sed vel lectus quis arcu venenatis aliquet. Sed id lorem ut ipsum consectetur consectetur. Pellentesque efficitur nisi tincidunt orci condimentum, quis auctor massa gravida. In hac habitasse platea dictumst. In magna eros, condimentum nec interdum eget, vehicula nec mi.

Proin vehicula fringilla leo id pretium. Phasellus malesuada ligula urna, sit amet venenatis elit interdum et. Suspendisse urna elit, rhoncus nec luctus vel, imperdiet vitae libero. Duis condimentum nunc magna, sed posuere quam egestas vel. Donec consequat hendrerit risus sit amet commodo. Cras tincidunt vestibulum lectus nec dictum. Donec sed augue scelerisque, luctus orci nec, molestie leo. Duis at libero ullamcorper, congue mauris vel, dignissim erat. Morbi eu iaculis nisl, ut luctus velit. Cras tristique gravida turpis.

Proin eleifend quam sit amet massa congue, in congue tellus efficitur. Donec eleifend nulla et mattis pharetra. Curabitur laoreet hendrerit varius. Curabitur pretium est gravida, malesuada mauris quis, maximus turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus congue tellus quis ultricies ullamcorper. Integer eleifend ligula eu libero consectetur egestas. Vestibulum ornare porta feugiat. Aliquam erat volutpat. Nunc sit amet ante eget ex egestas dapibus sit amet eget dui. Sed sit amet nibh orci.

Donec volutpat quis ligula eget blandit. Etiam nec fermentum diam. Praesent sed vehicula enim, ut faucibus lorem. Proin quis bibendum quam, quis blandit nunc. Vestibulum auctor id tortor vel consectetur. Aliquam vitae elit et urna viverra consequat. Fusce quis maximus magna. Proin eu pellentesque augue, sed malesuada orci. Vestibulum in efficitur nisl, quis blandit justo. Integer non quam vel orci venenatis mattis. Nunc id sapien ultrices, molestie felis id, dictum felis. Proin porta gravida quam at sodales. Nullam pharetra viverra efficitur. Vivamus ut est id tellus sollicitudin tempus. 


Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id dolor eget lectus volutpat viverra. Suspendisse potenti. Nulla sed nunc venenatis, sollicitudin quam porttitor, ultricies nunc. Nullam tempor, urna lobortis bibendum vulputate, turpis leo elementum nulla, eget fermentum metus dolor quis lacus. Mauris arcu mi, elementum sed arcu et, consequat congue sapien. Etiam eu aliquam purus. Aliquam et metus sed ipsum vehicula ullamcorper. Duis eu hendrerit odio. Proin sed nulla vehicula, pellentesque nibh sed, commodo dui. Duis vulputate leo at tellus sagittis, et euismod est congue. Curabitur tempor neque nulla, in pretium mauris imperdiet eu. Vestibulum eu mauris nunc. Nulla feugiat convallis nunc vel placerat. Nullam volutpat porta lectus, id placerat elit fermentum quis. Quisque elementum, sapien non aliquet consectetur, velit nisl dictum nisl, quis faucibus odio nisi sit amet arcu.

Vivamus sit amet sodales purus. Phasellus sem lorem, cursus et felis vel, eleifend egestas nunc. Donec pretium imperdiet magna, faucibus euismod tortor ultricies nec. Nullam pulvinar fermentum purus at dignissim. Praesent in metus nec lorem scelerisque pulvinar sed et libero. Duis sagittis at dui vitae cursus. Quisque ut orci eros. Sed vel lectus quis arcu venenatis aliquet. Sed id lorem ut ipsum consectetur consectetur. Pellentesque efficitur nisi tincidunt orci condimentum, quis auctor massa gravida. In hac habitasse platea dictumst. In magna eros, condimentum nec interdum eget, vehicula nec mi.

Proin vehicula fringilla leo id pretium. Phasellus malesuada ligula urna, sit amet venenatis elit interdum et. Suspendisse urna elit, rhoncus nec luctus vel, imperdiet vitae libero. Duis condimentum nunc magna, sed posuere quam egestas vel. Donec consequat hendrerit risus sit amet commodo. Cras tincidunt vestibulum lectus nec dictum. Donec sed augue scelerisque, luctus orci nec, molestie leo. Duis at libero ullamcorper, congue mauris vel, dignissim erat. Morbi eu iaculis nisl, ut luctus velit. Cras tristique gravida turpis.

Proin eleifend quam sit amet massa congue, in congue tellus efficitur. Donec eleifend nulla et mattis pharetra. Curabitur laoreet hendrerit varius. Curabitur pretium est gravida, malesuada mauris quis, maximus turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus congue tellus quis ultricies ullamcorper. Integer eleifend ligula eu libero consectetur egestas. Vestibulum ornare porta feugiat. Aliquam erat volutpat. Nunc sit amet ante eget ex egestas dapibus sit amet eget dui. Sed sit amet nibh orci.

Donec volutpat quis ligula eget blandit. Etiam nec fermentum diam. Praesent sed vehicula enim, ut faucibus lorem. Proin quis bibendum quam, quis blandit nunc. Vestibulum auctor id tortor vel consectetur. Aliquam vitae elit et urna viverra consequat. Fusce quis maximus magna. Proin eu pellentesque augue, sed malesuada orci. Vestibulum in efficitur nisl, quis blandit justo. Integer non quam vel orci venenatis mattis. Nunc id sapien ultrices, molestie felis id, dictum felis. Proin porta gravida quam at sodales. Nullam pharetra viverra efficitur. Vivamus ut est id tellus sollicitudin tempus. 


Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id dolor eget lectus volutpat viverra. Suspendisse potenti. Nulla sed nunc venenatis, sollicitudin quam porttitor, ultricies nunc. Nullam tempor, urna lobortis bibendum vulputate, turpis leo elementum nulla, eget fermentum metus dolor quis lacus. Mauris arcu mi, elementum sed arcu et, consequat congue sapien. Etiam eu aliquam purus. Aliquam et metus sed ipsum vehicula ullamcorper. Duis eu hendrerit odio. Proin sed nulla vehicula, pellentesque nibh sed, commodo dui. Duis vulputate leo at tellus sagittis, et euismod est congue. Curabitur tempor neque nulla, in pretium mauris imperdiet eu. Vestibulum eu mauris nunc. Nulla feugiat convallis nunc vel placerat. Nullam volutpat porta lectus, id placerat elit fermentum quis. Quisque elementum, sapien non aliquet consectetur, velit nisl dictum nisl, quis faucibus odio nisi sit amet arcu.

Vivamus sit amet sodales purus. Phasellus sem lorem, cursus et felis vel, eleifend egestas nunc. Donec pretium imperdiet magna, faucibus euismod tortor ultricies nec. Nullam pulvinar fermentum purus at dignissim. Praesent in metus nec lorem scelerisque pulvinar sed et libero. Duis sagittis at dui vitae cursus. Quisque ut orci eros. Sed vel lectus quis arcu venenatis aliquet. Sed id lorem ut ipsum consectetur consectetur. Pellentesque efficitur nisi tincidunt orci condimentum, quis auctor massa gravida. In hac habitasse platea dictumst. In magna eros, condimentum nec interdum eget, vehicula nec mi.

Proin vehicula fringilla leo id pretium. Phasellus malesuada ligula urna, sit amet venenatis elit interdum et. Suspendisse urna elit, rhoncus nec luctus vel, imperdiet vitae libero. Duis condimentum nunc magna, sed posuere quam egestas vel. Donec consequat hendrerit risus sit amet commodo. Cras tincidunt vestibulum lectus nec dictum. Donec sed augue scelerisque, luctus orci nec, molestie leo. Duis at libero ullamcorper, congue mauris vel, dignissim erat. Morbi eu iaculis nisl, ut luctus velit. Cras tristique gravida turpis.

Proin eleifend quam sit amet massa congue, in congue tellus efficitur. Donec eleifend nulla et mattis pharetra. Curabitur laoreet hendrerit varius. Curabitur pretium est gravida, malesuada mauris quis, maximus turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus congue tellus quis ultricies ullamcorper. Integer eleifend ligula eu libero consectetur egestas. Vestibulum ornare porta feugiat. Aliquam erat volutpat. Nunc sit amet ante eget ex egestas dapibus sit amet eget dui. Sed sit amet nibh orci.

Donec volutpat quis ligula eget blandit. Etiam nec fermentum diam. Praesent sed vehicula enim, ut faucibus lorem. Proin quis bibendum quam, quis blandit nunc. Vestibulum auctor id tortor vel consectetur. Aliquam vitae elit et urna viverra consequat. Fusce quis maximus magna. Proin eu pellentesque augue, sed malesuada orci. Vestibulum in efficitur nisl, quis blandit justo. Integer non quam vel orci venenatis mattis. Nunc id sapien ultrices, molestie felis id, dictum felis. Proin porta gravida quam at sodales. Nullam pharetra viverra efficitur. Vivamus ut est id tellus sollicitudin tempus. 


Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id dolor eget lectus volutpat viverra. Suspendisse potenti. Nulla sed nunc venenatis, sollicitudin quam porttitor, ultricies nunc. Nullam tempor, urna lobortis bibendum vulputate, turpis leo elementum nulla, eget fermentum metus dolor quis lacus. Mauris arcu mi, elementum sed arcu et, consequat congue sapien. Etiam eu aliquam purus. Aliquam et metus sed ipsum vehicula ullamcorper. Duis eu hendrerit odio. Proin sed nulla vehicula, pellentesque nibh sed, commodo dui. Duis vulputate leo at tellus sagittis, et euismod est congue. Curabitur tempor neque nulla, in pretium mauris imperdiet eu. Vestibulum eu mauris nunc. Nulla feugiat convallis nunc vel placerat. Nullam volutpat porta lectus, id placerat elit fermentum quis. Quisque elementum, sapien non aliquet consectetur, velit nisl dictum nisl, quis faucibus odio nisi sit amet arcu.

Vivamus sit amet sodales purus. Phasellus sem lorem, cursus et felis vel, eleifend egestas nunc. Donec pretium imperdiet magna, faucibus euismod tortor ultricies nec. Nullam pulvinar fermentum purus at dignissim. Praesent in metus nec lorem scelerisque pulvinar sed et libero. Duis sagittis at dui vitae cursus. Quisque ut orci eros. Sed vel lectus quis arcu venenatis aliquet. Sed id lorem ut ipsum consectetur consectetur. Pellentesque efficitur nisi tincidunt orci condimentum, quis auctor massa gravida. In hac habitasse platea dictumst. In magna eros, condimentum nec interdum eget, vehicula nec mi.

Proin vehicula fringilla leo id pretium. Phasellus malesuada ligula urna, sit amet venenatis elit interdum et. Suspendisse urna elit, rhoncus nec luctus vel, imperdiet vitae libero. Duis condimentum nunc magna, sed posuere quam egestas vel. Donec consequat hendrerit risus sit amet commodo. Cras tincidunt vestibulum lectus nec dictum. Donec sed augue scelerisque, luctus orci nec, molestie leo. Duis at libero ullamcorper, congue mauris vel, dignissim erat. Morbi eu iaculis nisl, ut luctus velit. Cras tristique gravida turpis.

Proin eleifend quam sit amet massa congue, in congue tellus efficitur. Donec eleifend nulla et mattis pharetra. Curabitur laoreet hendrerit varius. Curabitur pretium est gravida, malesuada mauris quis, maximus turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus congue tellus quis ultricies ullamcorper. Integer eleifend ligula eu libero consectetur egestas. Vestibulum ornare porta feugiat. Aliquam erat volutpat. Nunc sit amet ante eget ex egestas dapibus sit amet eget dui. Sed sit amet nibh orci.

Donec volutpat quis ligula eget blandit. Etiam nec fermentum diam. Praesent sed vehicula enim, ut faucibus lorem. Proin quis bibendum quam, quis blandit nunc. Vestibulum auctor id tortor vel consectetur. Aliquam vitae elit et urna viverra consequat. Fusce quis maximus magna. Proin eu pellentesque augue, sed malesuada orci. Vestibulum in efficitur nisl, quis blandit justo. Integer non quam vel orci venenatis mattis. Nunc id sapien ultrices, molestie felis id, dictum felis. Proin porta gravida quam at sodales. Nullam pharetra viverra efficitur. Vivamus ut est id tellus sollicitudin tempus. 
</div>
    </>
  );
}

export default App;
